ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG docker_credential_gcr_version=2.1.0

RUN set -ex && \
    apk add --no-cache --update curl tar && \
    curl -fsSL "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v${docker_credential_gcr_version}/docker-credential-gcr_linux_amd64-${docker_credential_gcr_version}.tar.gz" \
    | tar -xzf- docker-credential-gcr && \
    mv docker-credential-gcr /usr/local/bin/ && \
    docker-credential-gcr version && \
    docker-credential-gcr configure-docker --include-artifact-registry && \
    chown -R user. /home/user/.docker
