// Copyright 2022 tsuru authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: api/v1alpha1/build_service.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployOrigin int32

const (
	DeployOrigin_DEPLOY_ORIGIN_UNSPECIFIED     DeployOrigin = 0
	DeployOrigin_DEPLOY_ORIGIN_SOURCE_FILES    DeployOrigin = 1 // tsuru app deploy ... /path/to/my/files.sh
	DeployOrigin_DEPLOY_ORIGIN_CONTAINER_IMAGE DeployOrigin = 2 // tsuru app deploy ... -i registry.example.com/tsuru/my-app:staging
	DeployOrigin_DEPLOY_ORIGIN_DOCKERFILE      DeployOrigin = 3 // tsuru app deploy --dockerfile Dockerfile --dockerfile-context ./
	DeployOrigin_DEPLOY_ORIGIN_CONTAINERFILE   DeployOrigin = 3 // alias for containerfile :P
)

// Enum value maps for DeployOrigin.
var (
	DeployOrigin_name = map[int32]string{
		0: "DEPLOY_ORIGIN_UNSPECIFIED",
		1: "DEPLOY_ORIGIN_SOURCE_FILES",
		2: "DEPLOY_ORIGIN_CONTAINER_IMAGE",
		3: "DEPLOY_ORIGIN_DOCKERFILE",
		// Duplicate value: 3: "DEPLOY_ORIGIN_CONTAINERFILE",
	}
	DeployOrigin_value = map[string]int32{
		"DEPLOY_ORIGIN_UNSPECIFIED":     0,
		"DEPLOY_ORIGIN_SOURCE_FILES":    1,
		"DEPLOY_ORIGIN_CONTAINER_IMAGE": 2,
		"DEPLOY_ORIGIN_DOCKERFILE":      3,
		"DEPLOY_ORIGIN_CONTAINERFILE":   3,
	}
)

func (x DeployOrigin) Enum() *DeployOrigin {
	p := new(DeployOrigin)
	*p = x
	return p
}

func (x DeployOrigin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeployOrigin) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1alpha1_build_service_proto_enumTypes[0].Descriptor()
}

func (DeployOrigin) Type() protoreflect.EnumType {
	return &file_api_v1alpha1_build_service_proto_enumTypes[0]
}

func (x DeployOrigin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeployOrigin.Descriptor instead.
func (DeployOrigin) EnumDescriptor() ([]byte, []int) {
	return file_api_v1alpha1_build_service_proto_rawDescGZIP(), []int{0}
}

type BuildRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*BuildRequest_BuildParams
	//	*BuildRequest_ChunkData
	Data isBuildRequest_Data `protobuf_oneof:"data"`
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_build_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_build_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_build_service_proto_rawDescGZIP(), []int{0}
}

func (m *BuildRequest) GetData() isBuildRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *BuildRequest) GetBuildParams() *BuildParameters {
	if x, ok := x.GetData().(*BuildRequest_BuildParams); ok {
		return x.BuildParams
	}
	return nil
}

func (x *BuildRequest) GetChunkData() []byte {
	if x, ok := x.GetData().(*BuildRequest_ChunkData); ok {
		return x.ChunkData
	}
	return nil
}

type isBuildRequest_Data interface {
	isBuildRequest_Data()
}

type BuildRequest_BuildParams struct {
	// BuildParams are the parameters to build and push the container image.
	BuildParams *BuildParameters `protobuf:"bytes,1,opt,name=build_params,json=buildParams,proto3,oneof"`
}

type BuildRequest_ChunkData struct {
	// ChunkData is a chunk of the app's source context (source code or
	// Dockerfile context).
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*BuildRequest_BuildParams) isBuildRequest_Data() {}

func (*BuildRequest_ChunkData) isBuildRequest_Data() {}

type BuildParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// DeployOrigin indicates how the application is being deployed.
	DeployOrigin DeployOrigin `protobuf:"varint,1,opt,name=deploy_origin,json=deployOrigin,proto3,enum=v1alpha1.DeployOrigin" json:"deploy_origin,omitempty"`
	// SourceImage is the source container image name.
	//
	// When deploy is from app's source code (DEPLOY_ORIGIN_SOURCE_FILES), it holds
	// the plataform's container image (e.g. docker.io/tsuru/scratch:latest).
	// When deploy is from container image (DEPLOY_ORIGIN_CONTAINER_IMAGE), it holds
	// the app's container image (e.g. registry.example.com/company/app:v100).
	// Otherwise it's empty.
	SourceImage string `protobuf:"bytes,2,opt,name=source_image,json=sourceImage,proto3" json:"source_image,omitempty"`
	// DestinationImages are the tags of the container image after build.
	DestinationImages []string `protobuf:"bytes,3,rep,name=destination_images,json=destinationImages,proto3" json:"destination_images,omitempty"`
}

func (x *BuildParameters) Reset() {
	*x = BuildParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_build_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildParameters) ProtoMessage() {}

func (x *BuildParameters) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_build_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildParameters.ProtoReflect.Descriptor instead.
func (*BuildParameters) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_build_service_proto_rawDescGZIP(), []int{1}
}

func (x *BuildParameters) GetDeployOrigin() DeployOrigin {
	if x != nil {
		return x.DeployOrigin
	}
	return DeployOrigin_DEPLOY_ORIGIN_UNSPECIFIED
}

func (x *BuildParameters) GetSourceImage() string {
	if x != nil {
		return x.SourceImage
	}
	return ""
}

func (x *BuildParameters) GetDestinationImages() []string {
	if x != nil {
		return x.DestinationImages
	}
	return nil
}

type BuildResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*BuildResponse_Output
	//	*BuildResponse_TsuruConfig
	Data isBuildResponse_Data `protobuf_oneof:"data"`
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_build_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_build_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_build_service_proto_rawDescGZIP(), []int{2}
}

func (m *BuildResponse) GetData() isBuildResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *BuildResponse) GetOutput() string {
	if x, ok := x.GetData().(*BuildResponse_Output); ok {
		return x.Output
	}
	return ""
}

func (x *BuildResponse) GetTsuruConfig() *TsuruConfig {
	if x, ok := x.GetData().(*BuildResponse_TsuruConfig); ok {
		return x.TsuruConfig
	}
	return nil
}

type isBuildResponse_Data interface {
	isBuildResponse_Data()
}

type BuildResponse_Output struct {
	// Output is the progress messages during the build and push phase.
	Output string `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type BuildResponse_TsuruConfig struct {
	// TsuruConfig is the configuration of the application.
	TsuruConfig *TsuruConfig `protobuf:"bytes,2,opt,name=tsuru_config,json=tsuruConfig,proto3,oneof"`
}

func (*BuildResponse_Output) isBuildResponse_Data() {}

func (*BuildResponse_TsuruConfig) isBuildResponse_Data() {}

type TsuruConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Procfile definition found during the build.
	Procfile string `protobuf:"bytes,1,opt,name=procfile,proto3" json:"procfile,omitempty"`
	// TsuruYAML definition found during the build.
	TsuruYaml string `protobuf:"bytes,2,opt,name=tsuru_yaml,json=tsuruYaml,proto3" json:"tsuru_yaml,omitempty"`
}

func (x *TsuruConfig) Reset() {
	*x = TsuruConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_build_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TsuruConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsuruConfig) ProtoMessage() {}

func (x *TsuruConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_build_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsuruConfig.ProtoReflect.Descriptor instead.
func (*TsuruConfig) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_build_service_proto_rawDescGZIP(), []int{3}
}

func (x *TsuruConfig) GetProcfile() string {
	if x != nil {
		return x.Procfile
	}
	return ""
}

func (x *TsuruConfig) GetTsuruYaml() string {
	if x != nil {
		return x.TsuruYaml
	}
	return ""
}

var File_api_v1alpha1_build_service_proto protoreflect.FileDescriptor

var file_api_v1alpha1_build_service_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x22, 0x77, 0x0a, 0x0c,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0c,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x48, 0x00, 0x52,
	0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0a,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x42, 0x06, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa0, 0x01, 0x0a, 0x0f, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x3b, 0x0a, 0x0d, 0x64, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x5f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x16, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x22, 0x6d, 0x0a, 0x0d, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x3a, 0x0a, 0x0c, 0x74, 0x73, 0x75, 0x72, 0x75, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x54, 0x73, 0x75, 0x72, 0x75, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x48, 0x00, 0x52, 0x0b, 0x74, 0x73, 0x75, 0x72, 0x75, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42,
	0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x48, 0x0a, 0x0b, 0x54, 0x73, 0x75, 0x72, 0x75,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x63, 0x66, 0x69,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x63, 0x66, 0x69,
	0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x73, 0x75, 0x72, 0x75, 0x5f, 0x79, 0x61, 0x6d, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x73, 0x75, 0x72, 0x75, 0x59, 0x61, 0x6d,
	0x6c, 0x2a, 0xb3, 0x01, 0x0a, 0x0c, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x4f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x12, 0x1d, 0x0a, 0x19, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x5f, 0x4f, 0x52, 0x49,
	0x47, 0x49, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x5f, 0x4f, 0x52, 0x49, 0x47,
	0x49, 0x4e, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x53, 0x10,
	0x01, 0x12, 0x21, 0x0a, 0x1d, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x5f, 0x4f, 0x52, 0x49, 0x47,
	0x49, 0x4e, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x5f, 0x49, 0x4d, 0x41,
	0x47, 0x45, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x5f, 0x4f,
	0x52, 0x49, 0x47, 0x49, 0x4e, 0x5f, 0x44, 0x4f, 0x43, 0x4b, 0x45, 0x52, 0x46, 0x49, 0x4c, 0x45,
	0x10, 0x03, 0x12, 0x1f, 0x0a, 0x1b, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x5f, 0x4f, 0x52, 0x49,
	0x47, 0x49, 0x4e, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x46, 0x49, 0x4c,
	0x45, 0x10, 0x03, 0x1a, 0x02, 0x10, 0x01, 0x32, 0x47, 0x0a, 0x05, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x12, 0x3e, 0x0a, 0x05, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x16, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74,
	0x73, 0x75, 0x72, 0x75, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2d, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1alpha1_build_service_proto_rawDescOnce sync.Once
	file_api_v1alpha1_build_service_proto_rawDescData = file_api_v1alpha1_build_service_proto_rawDesc
)

func file_api_v1alpha1_build_service_proto_rawDescGZIP() []byte {
	file_api_v1alpha1_build_service_proto_rawDescOnce.Do(func() {
		file_api_v1alpha1_build_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1alpha1_build_service_proto_rawDescData)
	})
	return file_api_v1alpha1_build_service_proto_rawDescData
}

var file_api_v1alpha1_build_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1alpha1_build_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1alpha1_build_service_proto_goTypes = []interface{}{
	(DeployOrigin)(0),       // 0: v1alpha1.DeployOrigin
	(*BuildRequest)(nil),    // 1: v1alpha1.BuildRequest
	(*BuildParameters)(nil), // 2: v1alpha1.BuildParameters
	(*BuildResponse)(nil),   // 3: v1alpha1.BuildResponse
	(*TsuruConfig)(nil),     // 4: v1alpha1.TsuruConfig
}
var file_api_v1alpha1_build_service_proto_depIdxs = []int32{
	2, // 0: v1alpha1.BuildRequest.build_params:type_name -> v1alpha1.BuildParameters
	0, // 1: v1alpha1.BuildParameters.deploy_origin:type_name -> v1alpha1.DeployOrigin
	4, // 2: v1alpha1.BuildResponse.tsuru_config:type_name -> v1alpha1.TsuruConfig
	1, // 3: v1alpha1.Build.Build:input_type -> v1alpha1.BuildRequest
	3, // 4: v1alpha1.Build.Build:output_type -> v1alpha1.BuildResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1alpha1_build_service_proto_init() }
func file_api_v1alpha1_build_service_proto_init() {
	if File_api_v1alpha1_build_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1alpha1_build_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_build_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_build_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_build_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TsuruConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_v1alpha1_build_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*BuildRequest_BuildParams)(nil),
		(*BuildRequest_ChunkData)(nil),
	}
	file_api_v1alpha1_build_service_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*BuildResponse_Output)(nil),
		(*BuildResponse_TsuruConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1alpha1_build_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1alpha1_build_service_proto_goTypes,
		DependencyIndexes: file_api_v1alpha1_build_service_proto_depIdxs,
		EnumInfos:         file_api_v1alpha1_build_service_proto_enumTypes,
		MessageInfos:      file_api_v1alpha1_build_service_proto_msgTypes,
	}.Build()
	File_api_v1alpha1_build_service_proto = out.File
	file_api_v1alpha1_build_service_proto_rawDesc = nil
	file_api_v1alpha1_build_service_proto_goTypes = nil
	file_api_v1alpha1_build_service_proto_depIdxs = nil
}
