name: Go
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - uses: actions/checkout@v1

    - run: make integration

  deploy:
    if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - uses: actions/checkout@v1

    - name: Get tag
      id: get_tag
      run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: make TAG=${{ steps.get_tag.outputs.TAG }} push

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'

    - name: packagecloud
      env:
        PACKAGE_NAME: deploy-agent
        PACKAGECLOUD_TOKEN: ${{secrets.PACKAGECLOUD_TOKEN}}
      run: |
        curl -sL https://raw.githubusercontent.com/tsuru/push-to-packagecloud/master/push-github.sh | bash
